const data = {
  products: [
    {
      id: 1,
      name: 'Product 1',
      slug: 'product-1',
      category: 'Keyboard',
      brand: 'Gigabyte',
      description: 'Short description',
      price: 600,
      imageUrl: '/images/product-1.jpg',
      stockAmount: 10,
      isFeatured: true,
      isVisible: true,
      isOneSale: false,
      salePrice: 500,
      saleStarts: 'start-date-2022',
      saleEnds: 'end-date-2022',
      attributes: {
        color: ['black', 'white'],
        switch: 1,
      },
      rating: 4.5,
      reviewCount: 10,
    },
    {
      id: 2,
      name: 'Product 2',
      slug: 'product-2',
      category: 'Keyboard',
      brand: 'Gigabyte',
      description: 'Short description',
      price: 600,
      imageUrl: '/images/product-2.jpg',
      stockAmount: 10,
      isFeatured: true,
      isVisible: true,
      isOneSale: false,
      salePrice: 500,
      saleStarts: 'start-date-2022',
      saleEnds: 'end-date-2022',
      attributes: {
        color: ['black', 'white'],
        switch: 1,
      },
      rating: 4.5,
      reviewCount: 10,
    },
    {
      id: 3,
      name: 'Product 3',
      slug: 'product-3',
      category: 'Mouse',
      brand: 'Gigabyte',
      description: 'Short description',
      price: 600,
      imageUrl: '/images/product-3.jpg',
      stockAmount: 10,
      isFeatured: true,
      isVisible: true,
      isOneSale: false,
      salePrice: 500,
      saleStarts: 'start-date-2022',
      saleEnds: 'end-date-2022',
      attributes: {
        color: ['black', 'white'],
        switch: 1,
      },
      rating: 4.5,
      reviewCount: 10,
    },
    {
      id: 4,
      name: 'Product 4',
      slug: 'product-4',
      category: 'Mouse',
      brand: 'Gigabyte',
      description: 'Short description',
      price: 600,
      imageUrl: '/images/product-4.jpg',
      stockAmount: 10,
      isFeatured: true,
      isVisible: true,
      isOneSale: false,
      salePrice: 500,
      saleStarts: 'start-date-2022',
      saleEnds: 'end-date-2022',
      attributes: {
        color: ['black', 'white'],
        switch: 1,
      },
      rating: 4.5,
      reviewCount: 10,
    },
    {
      id: 5,
      name: 'Product 5',
      slug: 'product-5',
      category: 'Keyboard',
      brand: 'Asus',
      description: 'Short description',
      price: 600,
      imageUrl: '/images/product-5.jpg',
      stockAmount: 10,
      isFeatured: true,
      isVisible: true,
      isOneSale: false,
      salePrice: 500,
      saleStarts: 'start-date-2022',
      saleEnds: 'end-date-2022',
      attributes: {
        color: ['black', 'white'],
        switch: 1,
      },
      rating: 4.5,
      reviewCount: 10,
    },
    {
      id: 6,
      name: 'Product 6',
      category: 'Keyboard',
      slug: 'product-6',
      brand: 'Asus',
      description: 'Short description',
      price: 600,
      imageUrl: '/images/product-6.jpg',
      stockAmount: 10,
      isFeatured: true,
      isVisible: true,
      isOneSale: false,
      salePrice: 500,
      saleStarts: 'start-date-2022',
      saleEnds: 'end-date-2022',
      attributes: {
        color: ['black', 'white'],
        switch: 1,
      },
      rating: 4.5,
      reviewCount: 10,
    },
    {
      id: 7,
      name: 'Product 7',
      slug: 'product-7',
      category: 'Mouse',
      brand: 'Asus',
      description: 'Short description',
      price: 600,
      imageUrl: '/images/product-7.jpg',
      stockAmount: 10,
      isFeatured: true,
      isVisible: true,
      isOneSale: false,
      salePrice: 500,
      saleStarts: 'start-date-2022',
      saleEnds: 'end-date-2022',
      attributes: {
        color: ['black', 'white'],
        switch: 1,
      },
      rating: 4.5,
      reviewCount: 10,
    },
    {
      id: 8,
      name: 'Product 8',
      slug: 'product-8',
      category: 'Mouse',
      brand: 'Asus',
      description: 'Short description',
      price: 600,
      imageUrl: '/images/product-8.jpg',
      stockAmount: 10,
      isFeatured: true,
      isVisible: true,
      isOneSale: false,
      salePrice: 500,
      saleStarts: 'start-date-2022',
      saleEnds: 'end-date-2022',
      attributes: {
        color: ['black', 'white'],
        switch: 1,
      },
      rating: 4.5,
      reviewCount: 10,
    },
  ],
};

export default data;
